### ISSUE TITLE
str_plural first argument should be singular

### ISSUE THREAD

**Issue by vmitchell85** [jakebathman/twentypercenttimebot#2]
See: https://laravel.com/docs/5.5/helpers#method-str-plural

![image](https://user-images.githubusercontent.com/1248035/33497898-8cbb4100-d69d-11e7-9321-abd364a4e564.png)

**Comment by jakebathman** [comment]
Whoopsie, thanks.

**Comment by vmitchell85** [comment]
Just trying to help I swear... lol

**Comment by jakebathman** [comment]
I appreciate the second set of eyes on the details :) Keep 'em coming if you have anything else.
